### PR TITLE
Update to AKS 1.18

### LINKED ISSUE #17: Prep Baseline for AKS 1.18 (and Ubuntu 18.04)
The baseline is currently targeting 1.17.  1.18 is in preview and also comes with Ubuntu 18.04 by default.  Update the reference implementation to support 1.18.  We won't plan on merging this this until 1.18 is GA.

### PR DESCRIPTION
**Pull request by ckittel**
Prepping for AKS 1.18.

Fixes #17 

I've tested this end-to-end.

Feel free to review, but I won't be merging this in until 1.18 has gone GA (which should be soon)

### CODE REVIEW

**Review by ferantivero — APPROVED** [review]
LGTM 🚢

**Comment by ckittel** [comment]
Cool, thanks @ferantivero -- I'll do one more "end-to-end" on this after it goes GA.  Holding on merge until then.

**Comment by nitinkhandelwal26** [comment]
Please merge as 1.18.8 GA now..

**Comment by ckittel** [comment]
I'll do that on Monday. Thanks!

**Pull request merged**
