### PR TITLE
setup GitHub CD workflow

### PR DESCRIPTION
**Pull request by nish154**

### CODE REVIEW

**Comment by nish154** [comment]
closing

**Review by nish154 — COMMENTED** [review]
reviewed

**Comment by nish154** [comment]
approved

**Review by nish154 — COMMENTED** [review]
hello comment

**Comment by nish154** [comment]
approved

**Comment by nish154** [comment]
@nish154

**Comment by ckittel** [comment]
@nish154 -- wrong repo. Looks like you open this against the mspnp org instead of your personal fork :)  I'll just go ahead and close.

**Pull request closed without merging**
